---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "SDS348 Fall 2019"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

knitr::opts_chunk$set(echo = TRUE, eval = TRUE,fig.align="center",warning=FALSE,message=FALSE,fig.width=8, fig.height=5, linewidth=60)
options(tibble.width = 100,width = 100)
library("tidyverse", lib.loc="/usr/local/lib/R/site-library")
```

## Christine Bandela cmb5726


# Modeling

## Instructions

A knitted R Markdown document (as a PDF) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 11/24/2019. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(...) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)! 

Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in your final project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is acceptable, as long as you understand what the warnings mean).


## Guidelines and Rubric

- **0. (5 pts)** Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph.

  *For my modeling project, the dataset I will be using is 'midwest'. This dataset contains information on the demographics of the midwest counties. The variables that will be used are 'inmetro', 'state', 'county', 'popdensity', 'poptotal' and area.* 
  
- **1. (15 pts)** Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2).
```{R}
library(tidyverse)
library(ggplot2)
library("dplyr", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.4")
library(gridExtra)
ggplot(midwest, aes(x = poptotal, y = popdensity)) +
  geom_point(alpha = .5) + geom_density_2d(h=3) + coord_fixed() + facet_wrap(~state)

mid1<- midwest%>% group_by(state)

```

```{R}
m1<-manova(cbind(poptotal,popdensity)~state, data=midwest)
summary.aov(m1)
 midwest%>%group_by(state)%>%summarize(mean(poptotal),mean(popdensity))
 
```

```{R}
pairwise.t.test(midwest$poptotal,midwest$state,
                p.adj="none")
pairwise.t.test(midwest$popdensity,midwest$state,
                     p.adj="none")
```

*One MANOVA test with 2 numeric response variables and a categorical variable predictor with 5 levels was conducted, as well as, 10 t-tests for a total of 13 tests.A MANOVA test was used to study the effects on the categorical variable, 'state' (IL, IN, MI, OH, WI),  with two dependent numeric variables, 'poptotal' and 'popdensity'. Density plots did not show adequate results for multivariate normality. After studying the covariance matricies of each group showed relative homogeneity.  From the results the MANOVA test was proved to be a good technique. There were distinct differences found for the five midwest states on the two dependent variables. The Bonferroni method was used to control multiple comparisons of Type I error rates. This was done by conducting ANOVA testing  for each dependent variable and used after the MANOVA test. The univariate ANOVAs for 'poptotal' and 'popdensity' were also significant. Next a post hoc analysis was used to do a pairwise comparisons in order to see which 'state' differed in population total and population density. Of the five 'states' examined, they all differed significantly from each other by of population total and population density, as shown by the Bonferroni method.*



- **2. (10 pts)** Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).


```{R}
library(vegan)
dists<-midwest%>%select(poptotal, popdensity)%>%dist()
adonis(dists~state,data=midwest)


````
*The null hypothesis states that for the population total and population density, means of each state are equal. The alternative hypothesis states that for at least one dependent variable, at least one state mean is different.The randomized test conducted was a PERMANOVA. With this the question, "Does the population total affect distribution amoung states?" will be answered.  The resulting p-value was 0.573*


- **3. (35 pts)** Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.

    - Interpret the coefficient estimates (do not discuss significance) (10)
    - Plot the regression using `ggplot()`. If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (7)
    - Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (3)
    - Regardless, recompute regression results with robust standard errors via `coeftest(..., vcov=vcovHC(...))`. Discuss significance of results, including any changes from before/after robust SEs if applicable. (7)
    - What proportion of the variation in the outcome does your model explain? (3)
    - Finally, rerun the regression but without interactions (just main effects); compare this with the interaction model and the null model using a likelihood ratio test (4)
    
```{R}
library(tidyverse)
fit<-lm(poptotal~popdensity, data= midwest)
summary(fit)
midwest%>%ggplot(aes(popdensity,poptotal))+geom_point()+geom_smooth(method = 'lm',se=F)
 head(midwest,30)
 
library(lmtest)
library(sandwich)
  coeftest(fit)[,1:2]

coeftest(fit, vcov=vcovHC(fit))[,1:2] 


```
*The null hypothesis for this linear regression was that the population density does not explain variation in population total. The alternative hypothesis was that the population density does explain variation in population total. From these results we can see that the line of best fit is -1.207e+04 + 3.493e+01 (popdensity). Population density explains a significant amount of variation in poptotal. On average for every increase in popdensity, there is a  3.493e+01 increase in population total. Because population density is significant, we can reject the null hypothesis.*




- **4. (5 pts)** Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)

```{R}
fit<-lm(poptotal~popdensity, data= midwest)
summary(fit)
t.test(data=midwest, poptotal~inmetro, var.eq=T)
```

```{R}

fit1<-lm(poptotal ~ inmetro + popdensity, data=midwest)
summary(fit)
````
```{R}
library(sandwich); library(lmtest)
fit<-lm(poptotal~popdensity+inmetro,data=midwest)
bptest(fit)
summary(fit)$coef[,1:2]
 coeftest(fit, vcov = vcovHC(fit))[,1:2]
```
*Controlling for 'inmetro' there is a significant effect of population density on the population total. For every one unit increase in population density, the population tota increases 3.493e+01 on average, t= 4.887, df= 435, p < 0.001. However, after controlling for population density there is no difference in population total between inmetro and non-inmetro, t= 42.527 , df= 435, p=0.105 .*


- **5. (40 pts)** Perform a logistic regression predicting a binary categorical variable (if you don't have one, make/get one) from at least two explanatory variables (interaction not necessary). 

    - Interpret coefficient estimates in context (10)
    - Report a confusion matrix for your logistic regression (2)
    - Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5)
    - Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3)
    - Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (10)
    - Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)

```{R}
library(tidyverse); library(lmtest)
data(midwest)
data<-midwest
data$y<-ifelse(midwest$area==1,1,0)
fit<-glm(area~inmetro,data=data,family="binomial")
summary(fit)

 exp(coef(fit))%>%round(3)
```
```{R}
data$prob<-predict(fit,type="response") 
data$area<-as.factor(data$area)


ggplot(data, aes(inmetro,prob))+geom_jitter(aes(color=area),alpha=.5,size=3)+
  geom_rug(aes(color=area),sides="right")+geom_hline(yintercept=1)

```
```{R}
table(predict=as.numeric(data$prob>.5),truth=data$y)%>%addmargins

```
```{R}
mean(data[data$y==1,]$prob>.9)
```

```{R}
mean(data[data$y==0,]$prob<.9)
```
```{R}
tpr<-function(p)mean(data[data$y==1,]$prob>p)
fpr<-function(p)mean(data[data$y==0,]$prob>p)
data<-data[order(data$prob),]
prob<-data$prob
cuts<-unique(c(0,(prob[-1]+prob[-32])/2,1))
TPR<-sapply(cuts,tpr)
FPR<-sapply(cuts,fpr)

sens<-function(p,data=data, y=y) mean(data[data$y==1,]$prob>p)
spec<-function(p,data=data, y=y) mean(data[data$y==0,]$prob<p)

sensitivity<-sapply(seq(0,1,.01),sens,data)
specificity<-sapply(seq(0,1,.01),spec,data)

ROC1<-
  data.frame(cuts,TPR,FPR,TP=TPR*13,FP=FPR*19)%>%
  arrange(desc(cuts))
ROC1%>%round(5)

```
```{R}
ggplot(data, aes(inmetro,prob))+geom_point(aes(color=area),alpha=.5,size=3)+  geom_rug(aes(color=area),alpha=.5,sides="right")+  geom_hline(yintercept=c(.85))+theme(legend.position=c(.9,.8))
```
```{R}
widths<-diff(ROC1$FPR) 
heights<-(ROC1$TPR[-1]+ROC1$TPR[-length(ROC1$TPR)])/2
AUC<-sum(heights*widths)
AUC
```


*A logistic regression was conducted by predicting area from 'inmetro'. From these results we see that for every 1 unit increase in area, the odds of having a manual decrease by a factor of 0.902 (i.e. 9.8%)*

- **6. (10 pts)** Choose one variable you want to predict (can be one you used from before; either binary or continuous) and run a LASSO regression inputting all the rest of your variables as predictors. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., `lambda.1se`). Discuss which variables are retained. Perform 10-fold CV using this model: if response in binary, compare model's out-of-sample accuracy to that of your logistic regression in part 5; if response is numeric, compare the residual standard error (at the bottom of the summary output, aka RMSE): lower is better fit!
```{R}
f3<-lm(area~.,data=midwest)
yhat<-predict(f3)
```

```{R}
mean((midwest$area-yhat)^2) 

```


```{R}
library(glmnet)
data(midwest)
midwest$county = NULL
midwest$state = NULL
midwest$category = NULL

y<-as.matrix(midwest$area)
x<-midwest[,-1]%>%scale%>%as.matrix

cv<-cv.glmnet(x,y)
lasso1<-glmnet(x,y,lambda=cv$lambda.1se)
coef(lasso1)
```




```{R, echo=F}
## DO NOT DELETE THIS CHUNK!
sessionInfo()
Sys.time()
Sys.info()
```




